apiversion: eksctl.io/v1alpha5
kind: clusterconfig

metadata:
  name: spot-cluster
  region: ap-northeast-1

managedNodeGroups:


# instanceTypes defaults to [`m5.large`]
- name: spot
  spot: true
  ssh:
   publicKeyName: power
